### ISSUE TITLE
A few questions and a bug

### ISSUE THREAD

**Issue by ghost** [ManuelFay/ImageSearcher#1]
Thank you for your brilliant project, it is really good. A few errors (if there are any) or suggestions for improvement I would have:

That the search.html works for me I had to change the port under apiUrl: 'http://127.0.0.1:8000/get_best_images', to 5000.
 
Why are always only max. 50 hits displayed, I have 75k images, it can not show all?

the indexer does not index all files for me. e.g. only 46k of my 75k images. but they are all jpg / png in resolutions up to 48mp, but according to your code all jpeg jpg png should be captured

Why is my 8gb+ nvidia graphics card (cuda) not used at all when indexing, is that a bug?
the gpu load is always at 0-1%. It takes forever to index the images like this! 2-25it/s here!
With 50k+ images it just takes way too long!
The images are on a 2TB PCIe nvme ssd, 64gb ram and 8core cpu, that must be faster?

Why index again completely? That's crazy, wait 1h to days for 10 new images?
INFO:root:45636 files are indexed.
INFO:root:Re-indexing the image files in e:\\Pictures\\\.

With images over 4k resolution, the thumbnail generation in the browser is really slow. the search is sometimes not usable for minutes!

It would be really ingenious to be able to set the hits in the search. E.g. all hits, only top100 or only a list with file names, best downloadable.

Is there a possibility to specify multiple sources? like. Win C: D: E: or linux /home/pics /data/ etc.

A possibility to create own categories. For this it needs to my knowledge only a few pictures. E.g. Myself, 10-100 valid pictures, then the category Myself and it collects out of the 50k+ pictures all from yourself out.

A tutorial for noobs on how to set everything up on Windows 10 with conda for optimal efficiency:

My procedure was:
conda create --name ClipSearch python=3.8
conda activate ClipSearch
python -m pip install -U -r c:\ImageSearcher\dev_requirements.txt
customized search.yml
and a custom start_server.py

But what I do now with this Gunicorn for example?
If I enter the command from your page nothing happens!
For what do I need it? Also everything is very slow... How i use cuda and all cores?

ps
i have only beginner skills python programming, if you need something for analysis please describe exactly how to get the data
i use an online translator because eng is not my native language.
Hope you understand it anyway^^

**Comment by ManuelFay** [comment]
Thanks a lot for opening the issue ! I'll try to answer everything one by one, and will update several things ASAP (tmrw probably):

```That the search.html works for me I had to change the port under apiUrl: 'http://127.0.0.1:8000/get_best_images', to 5000.```
I am guessing you ran it with Flask. In practice (to deploy on a server etc), it can be a bit more robust to use Gunicorn which was set up for the port 8000, but Flask was still at 5000. I'll make the changes in the Readme, thanks for pointing this out !

```Why are always only max. 50 hits displayed, I have 75k images, it can not show all?```
The 50 hits is just a parameter that can be adjusted in the YAML config file for the API (n), or in the python function `searcher.rank_images(user_query, n=MAX_HITS`. When n is None, it returns a ranked list of all images, so your 75k can be returned in order. For the web interface, I thought it was best just to return the top 42 more or less, but feel free to adjust this number. I will add the parameter in the YML example config file !

```the indexer does not index all files for me. e.g. only 46k of my 75k images. but they are all jpg / png in resolutions up to 48mp, but according to your code all jpeg jpg png should be captured```

I have to figure out what is going on, my initial guess is that it does not match the uppercase JPG endings. I tested it with >100k images with it working so maybe that can be why, I will make the changes. If you can, I would be glad to have a short list of examples of filenames that were not indexed if it still doesn't work after my changes :) 

```
Why is my 8gb+ nvidia graphics card (cuda) not used at all when indexing, is that a bug?
the gpu load is always at 0-1%. It takes forever to index the images like this! 2-25it/s here!
With 50k+ images it just takes way too long!Why index again completely? That's crazy, wait 1h to days for 10 new images?
The images are on a 2TB PCIe nvme ssd, 64gb ram and 8core cpu, that must be faster?
```

Very good point, I wrote the library for myself initially and I don't have a GPU so I didn't configure the pytorch code to run on GPU. I will update it to work on GPU and it should be a lot faster ! Note that in my case, the bottleneck is more in loading the image than in processing it with the neural network (as my RAM runs out fairly quickly). I can not test easily on GPU but there should be a very noticeable speedup. 

```Why index again completely? That's crazy, wait 1h to days for 10 new images? ```

It does not do that normally ;) If you add 10 new images, it just processes the 10 new ones. This is in the case that you did not move or suppress the pickle file with the names and embeddings of all procesed images. It says re-indexing to rescan the directory for new files but does not reprocess known ones.

```
It would be really ingenious to be able to set the hits in the search. E.g. all hits, only top100 or only a list with file names, best downloadable.
```
For more control, I recommend using the ImageSearcher directly through Python. There, you get an easy control over the number of returned hits (parameter `n`), and the rank_images function returns a list of the image paths. What the HTML does is simply load the images from their paths in your browser. I will try to add small features to the webpage, but am still fairly new to front-ends. The rest of what you say can be easily achieved by varying `n` or slightly updating the webpage. 

```
With images over 4k resolution, the thumbnail generation in the browser is really slow. the search is sometimes not usable for minutes!
```

I think that here, the problem is that the image quality is too large for your browser to easily load everything at once. I am not sure if the problem is when reshaping the image for the thumbnails or just during loading, I'll have to run tests but sadly, I am new  at front-end dev and will have to check if it's possible to load images in a lower quality for the thumbnails.

```
Is there a possibility to specify multiple sources? like. Win C: D: E: or linux /home/pics /data/ etc.
```
Yes, for now, just specify a store_path for your pickle file, and change the image path. Everything should be stored at the same place and be retrievable, when you run it one more time with image_dir_path=None (just refers to your stored images), and your store_path! 


```A possibility to create own categories. For this it needs to my knowledge only a few pictures. E.g. Myself, 10-100 valid pictures, then the category Myself and it collects out of the 50k+ pictures all from yourself out.```

Very nice idea, I wonder if by simply classifying the pre-generated embeddings it can work, or if it would require a different classification pipeline. I will give it a try, but do not expect this feature this week, I am a bit busy at the moment. I'll definitely give it a shot, thanks for the suggestion !

By the way, very nice English ! I will make the simple modifications very soon and will notify you !

**Comment by ManuelFay** [comment]
I will look into the classification idea a bit later, as well as the front end improvements (features + 4K image loading time in the browser).  The rest should be modified/fixed !

**Comment by ghost** [comment]
Thanks for your detailed explanation.

> I have to figure out what is going on, my initial guess is that it does not match the uppercase JPG endings. I tested it with >100k images with it working so maybe that can be why, I will make the changes. If you can, I would be glad to have a short list of examples of filenames that were not indexed if it still doesn't work after my changes :)


The file extensions did it.  I have extended self.accepted_formats = (".png", ".jpg", ".jpeg") with .PNG .JPG .Jpg and so on. Now it recognizes all files. Isn't it normally case insensitive?


> Very nice idea, I wonder if by simply classifying the pre-generated embeddings it can work, or if it would require a different classification pipeline. I will give it a try, but do not expect this feature this week, I am a bit busy at the moment. I'll definitely give it a shot, thanks for the suggestion !

In this article I think I read it. I hope that I had understood correctly.
https://blog.roboflow.com/how-to-use-openai-clip/



> `Why index again completely? That's crazy, wait 1h to days for 10 new images? `
> 
> It does not do that normally ;) If you add 10 new images, it just processes the 10 new ones. This is in the case that you did not move or suppress the pickle file with the names and embeddings of all procesed images. It says re-indexing to rescan the directory for new files but does not reprocess known ones.

Sorry, it was due to an error on my end. Had changed the path in my YML

**Comment by ManuelFay** [comment]
Great to here for the uppercase extensions, I made it case insensitive yesterday so it should be all good now if you pull the new version!

As for the link, I already leverage something like this, but for it to work on a class created from your own images (eg. your face), it can not work out-of-the-box since it is never trained with that data. What I was wondering was whether the image embedding was sufficiently precise to be able to run a simple classification algorithm without having to retrain the embeddings on the downstream classification task, but rather just train a network from the frozen embeddings themselves.

I closed the Issue but if you experience any trouble with the GPU or anything else, please do not hesitate to re-open it or mention it here !

Best,
Manuel

**Comment by ManuelFay** [comment]
@GitHub-23666 I created a new branch with the requested face recognition feature. #3 
It is still a work in progress but if you're still interested, you can begin to play around with it (beware, indexing all images at the beginning is a bit slow)
